politics_power:
  - политика
  - Путин
  - Медведев
  - Навальный
  - Трамп
  - Обама
  - Украина
  - санкции
  - коррупция
  - демократия
  - Березовский
  - Абрамович
family_relationships:
  - муж и жена
  - тёща
  - семья
  - любовь
  - свадьба
  - девушки
  - мужчины
work_professions:
  - работа
  - врачи
  - программист
  - сантехник
  - учитель
education_children:
  - школа
  - студент
  - студенты
  - дети
  - вовочка
  - егэ
army_police:
  - армия
  - война
  - милиция
  - полиция
  - гаи
  - фсб
it_internet:
  - интернет
  - telegram
  - windows
  - apple
  - мобильный
  - ии
  - Билл Гейтс
  - Вконтакте
character_cycles:
  - Штирлиц
  - чапаев
  - чукча
  - Рабинович
  - Винни-Пух
  - Чебурашка
  - Буратино
  - Гарри Поттер
  - Дед Мороз
everyday_life:
  - деньги
  - дача
  - соседи
  - транспорт
  - жкх
  - авто
  - маршрутка
  - автобус
  - такси
  - пиво
  - водка
  - новогодний
  - тв
  - кино
  - русский язык
animals:
  - кошки
  - собаки
  - животные
other:
  - юмор
  - о жизни
  - 1 апреля
  - 14 февраля
  - 23 февраля
  - 8 марта

