politics_power:
  - политика
  - Путин
  - Медведев
  - Навальный
  - Трамп
  - Обама
  - Украина
  - санкции
  - коррупция
  - демократия
  - Березовский
  - Абрамович
  - Прохоров
  - Валуев
soviet_history_politics:
  - Сталин
  - Брежнев
family_relationships:
  - муж и жена
  - тёща
  - семья
  - любовь
  - свадьба
sex_gender:
  - девушки
  - мужчины
  - секс
  - пошлые
  - блондинки
  - брюнетки
  - геи
work_professions:
  - работа
  - программист
  - сантехник
  - пожарный
education_children:
  - школа
  - студент
  - дети
  - вовочка
  - егэ
army_police:
  - армия
  - война
  - милиция
  - фсб
law_crime:
  - гаи
  - таможня
transport:
  - авто
  - авиация
  - поезд
  - метро
  - трамвай
  - троллейбус
  - автобус
  - маршрутка
  - такси
  - лифт
  - парашют
  - трактор
it_internet:
  - интернет
  - telegram
  - windows
  - apple
  - мобильный
  - ии
  - Билл Гейтс
  - Вконтакте
  - смс
  - твиттер
internet_memes:
  - мемы
literature_folklore_characters:
  - Штирлиц
  - чапаев
  - чукча
  - Рабинович
  - Винни-Пух
  - Чебурашка
  - Буратино
  - Гарри Поттер
  - Ржевский
  - Шерлок Холмс
  - армянское радио
  - золотая рыбка
  - Иван-царевич
  - Красная Шапочка
  - Колобок
  - Муму
  - богатыри
  - Карлсон
  - Пушкин
  - Адам и Ева
  - Донцова
  - Каренина
  - Мазай
  - Хоттабыч
  - Сусанин
  - Баба-Яга
media_popculture:
  - Дед Мороз
  - звёзды
  - тв
  - кино
  - фильмы
  - мультфильмы
  - покемоны
  - Чак Норрис
  - Куклачев
everyday_life:
  - погода
  - дача
  - соседи
  - отдых
  - рыбалка
  - охота
  - бесплатное
  - почта
  - приметы
consumer_services:
  - жкх
  - реклама
  - объявления
finance_economy:
  - деньги
  - налоги
  - кредиты
  - кризис
  - сбербанк
  - ммм
health_medicine:
  - врачи
  - аптека
  - грипп
  - пенсионеры
  - Онищенко
covid_pandemic:
  - коронавирус
alcohol_smoking_drugs:
  - водка
  - пиво
  - сигареты
  - наркотики
religion_holidays:
  - новогодний
  - 8 марта
  - 23 февраля
  - 1 апреля
  - 14 февраля
  - пасха
food_diet:
  - диета
  - веган
animals:
  - кошки
  - собаки
  - животные
  - тараканы
sport:
  - спорт
  - футбол
  - хоккей
  - Сочи 2014
cities_places:
  - Одесса
  - Москва
  - Челябинск
ethnic_regional:
  - новые русские
science_space:
  - космос
  - нанотехнологии
  - британские ученые
  - Перельман
textual_forms:
  - русский язык
  - инструкции
  - цитаты
absurd_philosophy:
  - юмор
  - о жизни
  - конец света
other: []
